/**
 * The committee lottery, ported from `shared/coordinator/src/committee_selection.rs`.
 *
 * Every round draws tie-breakers, verifiers and trainers from one shuffle keyed
 * by `Round.random_seed`, which is public on chain. That makes the roles
 * derivable by anyone reading the account, so showing them here reveals nothing
 * an observer could not already compute. It is also why this file must match
 * Rust exactly: a wrong port would label honest nodes with roles they were
 * never assigned. `scripts/verify-committee.ts` checks it against vectors
 * generated by the Rust implementation, and the build runs it.
 */

const SHUFFLE_ROUND_COUNT = 90
const COMMITTEE_SALT = 'committee'
const WITNESS_SALT = 'witness'
const MAX_WITNESSES = 32n

const K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
  0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
  0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
  0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
  0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
  0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
  0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
  0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
  0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
])

/** Synchronous because the shuffle needs 180 digests per index. */
export function sha256(...chunks: Uint8Array[]): Uint8Array {
  let total = 0
  for (const chunk of chunks) total += chunk.length
  const message = new Uint8Array(total)
  let at = 0
  for (const chunk of chunks) {
    message.set(chunk, at)
    at += chunk.length
  }

  const bitLength = message.length * 8
  const padded = new Uint8Array(((message.length + 9 + 63) >> 6) << 6)
  padded.set(message)
  padded[message.length] = 0x80
  const tail = new DataView(padded.buffer)
  tail.setUint32(padded.length - 4, bitLength >>> 0, false)
  tail.setUint32(padded.length - 8, Math.floor(bitLength / 0x100000000), false)

  const h = new Uint32Array([
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c,
    0x1f83d9ab, 0x5be0cd19,
  ])
  const w = new Uint32Array(64)
  const view = new DataView(padded.buffer)

  for (let block = 0; block < padded.length; block += 64) {
    for (let i = 0; i < 16; i += 1) w[i] = view.getUint32(block + i * 4, false)
    for (let i = 16; i < 64; i += 1) {
      const a = w[i - 15]
      const b = w[i - 2]
      const s0 = ((a >>> 7) | (a << 25)) ^ ((a >>> 18) | (a << 14)) ^ (a >>> 3)
      const s1 = ((b >>> 17) | (b << 15)) ^ ((b >>> 19) | (b << 13)) ^ (b >>> 10)
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) >>> 0
    }

    let [a, b, c, d, e, f, g, hh] = h
    for (let i = 0; i < 64; i += 1) {
      const s1 = ((e >>> 6) | (e << 26)) ^ ((e >>> 11) | (e << 21)) ^ ((e >>> 25) | (e << 7))
      const ch = (e & f) ^ (~e & g)
      const t1 = (hh + s1 + ch + K[i] + w[i]) >>> 0
      const s0 = ((a >>> 2) | (a << 30)) ^ ((a >>> 13) | (a << 19)) ^ ((a >>> 22) | (a << 10))
      const maj = (a & b) ^ (a & c) ^ (b & c)
      const t2 = (s0 + maj) >>> 0
      hh = g
      g = f
      f = e
      e = (d + t1) >>> 0
      d = c
      c = b
      b = a
      a = (t1 + t2) >>> 0
    }

    h[0] = (h[0] + a) >>> 0
    h[1] = (h[1] + b) >>> 0
    h[2] = (h[2] + c) >>> 0
    h[3] = (h[3] + d) >>> 0
    h[4] = (h[4] + e) >>> 0
    h[5] = (h[5] + f) >>> 0
    h[6] = (h[6] + g) >>> 0
    h[7] = (h[7] + hh) >>> 0
  }

  const out = new Uint8Array(32)
  const outView = new DataView(out.buffer)
  for (let i = 0; i < 8; i += 1) outView.setUint32(i * 4, h[i], false)
  return out
}

function u64le(value: bigint): Uint8Array {
  const out = new Uint8Array(8)
  new DataView(out.buffer).setBigUint64(0, value, true)
  return out
}

function readU64le(bytes: Uint8Array, at: number): bigint {
  return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getBigUint64(
    at,
    true,
  )
}

/** The eth2 swap-or-not shuffle, as `shared/core/src/swap_or_not.rs` runs it. */
export function computeShuffledIndex(
  index: bigint,
  indexCount: bigint,
  seed: Uint8Array,
): bigint {
  if (index >= indexCount) throw new Error('index out of range')

  let current = index
  for (let round = 0; round < SHUFFLE_ROUND_COUNT; round += 1) {
    const roundByte = new Uint8Array([round])
    const hash = sha256(seed, roundByte)
    const pivot = readU64le(hash, 0) % indexCount
    const flip = (pivot + indexCount - current) % indexCount
    const position = current > flip ? current : flip

    const positionBytes = new Uint8Array(4)
    new DataView(positionBytes.buffer).setUint32(0, Number(position / 256n), true)
    const source = sha256(seed, roundByte, positionBytes)

    const byte = source[Number((position % 256n) / 8n)]
    const bit = (byte >> Number(position % 8n)) % 2
    if (bit === 1) current = flip
  }

  return current
}

export type CommitteeRole = 'Tie breaker' | 'Verifier' | 'Trainer'

export type CommitteeAssignment = {
  index: number
  position: bigint
  role: CommitteeRole
  witness: boolean
}

export class CommitteeSelection {
  readonly tieBreakerNodes: bigint
  readonly verifierNodes: bigint
  readonly totalNodes: bigint
  readonly witnessNodes: bigint
  private readonly seed: Uint8Array

  private constructor(
    tieBreakerNodes: bigint,
    verifierNodes: bigint,
    totalNodes: bigint,
    witnessNodes: bigint,
    seed: Uint8Array,
  ) {
    this.tieBreakerNodes = tieBreakerNodes
    this.verifierNodes = verifierNodes
    this.totalNodes = totalNodes
    this.witnessNodes = witnessNodes
    this.seed = seed
  }

  static create(params: {
    tieBreakerNodes: number
    witnessNodes: number
    verificationPercent: number
    totalNodes: number
    randomSeed: bigint
  }): CommitteeSelection | null {
    const { tieBreakerNodes, witnessNodes, verificationPercent, totalNodes } =
      params
    if (totalNodes < tieBreakerNodes) return null
    if (witnessNodes !== 0 && totalNodes < witnessNodes) return null
    if (verificationPercent > 100) return null

    const freeNodes = totalNodes - tieBreakerNodes
    const verifierNodes = Math.floor((freeNodes * verificationPercent) / 100)

    return new CommitteeSelection(
      BigInt(tieBreakerNodes),
      BigInt(verifierNodes),
      BigInt(totalNodes),
      BigInt(witnessNodes),
      sha256(u64le(params.randomSeed)),
    )
  }

  private shuffled(index: bigint, salt: string): bigint {
    const salted = sha256(this.seed, new TextEncoder().encode(salt))
    return computeShuffledIndex(index, this.totalNodes, salted)
  }

  roleAt(position: bigint): CommitteeRole {
    if (position < this.tieBreakerNodes) return 'Tie breaker'
    if (position < this.tieBreakerNodes + this.verifierNodes) return 'Verifier'
    return 'Trainer'
  }

  isWitnessAt(position: bigint): boolean {
    return this.witnessNodes === 0n
      ? position < MAX_WITNESSES
      : position < this.witnessNodes
  }

  assign(index: number): CommitteeAssignment {
    const committeePosition = this.shuffled(BigInt(index), COMMITTEE_SALT)
    const witnessPosition = this.shuffled(BigInt(index), WITNESS_SALT)
    return {
      index,
      position: committeePosition,
      role: this.roleAt(committeePosition),
      witness: this.isWitnessAt(witnessPosition),
    }
  }

  assignAll(): CommitteeAssignment[] {
    const out: CommitteeAssignment[] = []
    for (let i = 0; i < Number(this.totalNodes); i += 1) out.push(this.assign(i))
    return out
  }
}
