/**
 * Byte offsets into the coordinator account.
 *
 * `CoordinatorAccount` is `#[repr(C)]` zero-copy, so this reads it by offset
 * rather than through Borsh. Every number here is generated by the Rust test at
 * `architectures/decentralized/solana-coordinator/programs/solana-coordinator/tests/web_layout.rs`
 * in leviathan-net. Reading the wrong offset does not throw, it renders a
 * plausible wrong number, so that test is what fails when the layout moves.
 */

export const DISCRIMINATOR = 8

export const MAX_CLIENTS = 256
export const MAX_WITNESSES = 32
export const RUN_ID_LEN = 32
export const CLIENT_VERSION_LEN = 96
export const NUM_STORED_ROUNDS = 4

export const SIZE = {
  account: 119152,
  instanceState: 119136,
  coordinator: 94048,
  epochState: 93360,
  config: 64,
  clientsState: 24624,
  round: 14112,
  epochClient: 72,
  ledgerClient: 96,
} as const

/** What `getProgramAccounts` filters on, and what the decoder refuses to read. */
export const ACCOUNT_SIZE = DISCRIMINATOR + SIZE.account

const STATE = DISCRIMINATOR + 8
const COORDINATOR = STATE + 360
const EPOCH_STATE = COORDINATOR + 672
const CLIENTS_STATE = STATE + 94408

export const AT = {
  version: DISCRIMINATOR + 0,
  nonce: DISCRIMINATOR + 119144,

  metadata: STATE + 0,
  clientVersion: STATE + 119034,

  runId: COORDINATOR + 0,
  runState: COORDINATOR + 32,
  model: COORDINATOR + 40,
  config: COORDINATOR + 592,
  progress: COORDINATOR + 656,
  runStateStartUnix: COORDINATOR + 94032,

  rounds: EPOCH_STATE + 0,
  epochClients: EPOCH_STATE + 56448,
  exitedClients: EPOCH_STATE + 74888,
  roundsHead: EPOCH_STATE + 93328,
  startStep: EPOCH_STATE + 93332,
  lastStep: EPOCH_STATE + 93336,
  startTimestamp: EPOCH_STATE + 93344,

  ledgerClients: CLIENTS_STATE + 0,
  nextActive: CLIENTS_STATE + 24584,
} as const

/** Offsets inside `CoordinatorConfig`, relative to `AT.config`. */
export const CONFIG_AT = {
  warmupTime: 0,
  cooldownTime: 8,
  maxRoundTrainTime: 16,
  roundWitnessTime: 24,
  globalBatchSizeWarmupTokens: 32,
  epochTime: 40,
  totalSteps: 48,
  initMinClients: 52,
  minClients: 54,
  witnessNodes: 56,
  globalBatchSizeStart: 58,
  globalBatchSizeEnd: 60,
  verificationPercent: 62,
} as const

/**
 * Offsets inside a `Round`, relative to the start of that round.
 *
 * `witnesses` is a `FixedVec`, which stores its `len` after the array rather
 * than before it, so the count sits at the end of the vector's span.
 */
export const ROUND_AT = {
  witnesses: 0,
  witnessesLen: 14080,
  dataIndex: 14088,
  randomSeed: 14096,
  height: 14104,
  clientsLen: 14108,
  tieBreakerTasks: 14110,
} as const

/** Offsets inside an epoch-roster `Client`. */
export const EPOCH_CLIENT_AT = {
  id: 0,
  state: 64,
  exitedHeight: 68,
} as const

/**
 * Offsets inside a ledger `Client`.
 *
 * A different struct from the epoch-roster one, indexed differently. Treating
 * the two as parallel is what let a convicted participant keep its bond
 * (wienerlabs/leviathan#15, finding 1), so they are named apart here.
 */
export const LEDGER_CLIENT_AT = {
  id: 0,
  earned: 72,
  slashed: 80,
  active: 88,
} as const

export const RUN_STATES = [
  'Uninitialized',
  'Waiting for members',
  'Warmup',
  'Round train',
  'Round witness',
  'Cooldown',
  'Finished',
  'Paused',
] as const

export const CLIENT_STATES = [
  'Healthy',
  'Dropped',
  'Withdrawn',
  'Ejected',
] as const

export type RunStateName = (typeof RUN_STATES)[number]
export type ClientStateName = (typeof CLIENT_STATES)[number]
